/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_lsm1987_egsnsplugin_EGSnsTwitter_ErrorCode */

#ifndef _Included_com_lsm1987_egsnsplugin_EGSnsTwitter_ErrorCode
#define _Included_com_lsm1987_egsnsplugin_EGSnsTwitter_ErrorCode
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
