/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_lsm1987_egsnsplugin_EGSnsTwitter */

#ifndef _Included_com_lsm1987_egsnsplugin_EGSnsTwitter
#define _Included_com_lsm1987_egsnsplugin_EGSnsTwitter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_lsm1987_egsnsplugin_EGSnsTwitter
 * Method:    nativeOnLoggedIn
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_lsm1987_egsnsplugin_EGSnsTwitter_nativeOnLoggedIn
  (JNIEnv *, jobject, jboolean);

#ifdef __cplusplus
}
#endif
#endif
